//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.SVC_BD {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="SVC_BD.IGeneral")]
    public interface IGeneral {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneral/GetDataTable", ReplyAction="http://tempuri.org/IGeneral/GetDataTableResponse")]
        System.Data.DataTable GetDataTable(System.Data.DataTable dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneral/GetDataTable", ReplyAction="http://tempuri.org/IGeneral/GetDataTableResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> GetDataTableAsync(System.Data.DataTable dt);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneral/ListarFiltrar", ReplyAction="http://tempuri.org/IGeneral/ListarFiltrarResponse")]
        System.Data.DataTable ListarFiltrar(string sNombreTabla, string sNombreSP, System.Data.DataTable DT_Param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneral/ListarFiltrar", ReplyAction="http://tempuri.org/IGeneral/ListarFiltrarResponse")]
        System.Threading.Tasks.Task<System.Data.DataTable> ListarFiltrarAsync(string sNombreTabla, string sNombreSP, System.Data.DataTable DT_Param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneral/Ins_Upd_Delete", ReplyAction="http://tempuri.org/IGeneral/Ins_Upd_DeleteResponse")]
        string Ins_Upd_Delete(string sNombreSP, string sIndAxn, System.Data.DataTable DT_Param);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/IGeneral/Ins_Upd_Delete", ReplyAction="http://tempuri.org/IGeneral/Ins_Upd_DeleteResponse")]
        System.Threading.Tasks.Task<string> Ins_Upd_DeleteAsync(string sNombreSP, string sIndAxn, System.Data.DataTable DT_Param);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface IGeneralChannel : Proyecto.SVC_BD.IGeneral, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class GeneralClient : System.ServiceModel.ClientBase<Proyecto.SVC_BD.IGeneral>, Proyecto.SVC_BD.IGeneral {
        
        public GeneralClient() {
        }
        
        public GeneralClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public GeneralClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public GeneralClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public System.Data.DataTable GetDataTable(System.Data.DataTable dt) {
            return base.Channel.GetDataTable(dt);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> GetDataTableAsync(System.Data.DataTable dt) {
            return base.Channel.GetDataTableAsync(dt);
        }
        
        public System.Data.DataTable ListarFiltrar(string sNombreTabla, string sNombreSP, System.Data.DataTable DT_Param) {
            return base.Channel.ListarFiltrar(sNombreTabla, sNombreSP, DT_Param);
        }
        
        public System.Threading.Tasks.Task<System.Data.DataTable> ListarFiltrarAsync(string sNombreTabla, string sNombreSP, System.Data.DataTable DT_Param) {
            return base.Channel.ListarFiltrarAsync(sNombreTabla, sNombreSP, DT_Param);
        }
        
        public string Ins_Upd_Delete(string sNombreSP, string sIndAxn, System.Data.DataTable DT_Param) {
            return base.Channel.Ins_Upd_Delete(sNombreSP, sIndAxn, DT_Param);
        }
        
        public System.Threading.Tasks.Task<string> Ins_Upd_DeleteAsync(string sNombreSP, string sIndAxn, System.Data.DataTable DT_Param) {
            return base.Channel.Ins_Upd_DeleteAsync(sNombreSP, sIndAxn, DT_Param);
        }
    }
}
